services:
  front-end:
    image: mbaanni/filmexa-frontend:latest
    container_name: filmexa-frontend
    restart: always
    ports:
      - 80:80
    networks:
      - shared-network

networks:
  shared-network:
    external: true
    name: filmexa-net
