services:
  front-end:
    image: mbaanni/filmexa-frontend:latest
    container_name: filmexa-frontend
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - shared-network
    volumes:
      - letsencrypt:/etc/letsencrypt
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 2s
      timeout: 2s
      retries: 15
      start_period: 5s


networks:
  shared-network:
    external: true
    name: filmexa-net
volumes:
  letsencrypt:
