server {
    listen 80;
    server_name _;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name _;

    ssl_certificate /etc/letsencrypt/live/filmexa.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/filmexa.duckdns.org/privkey.pem;

    location / {
        root /usr/share/nginx/html/en-US;
        try_files $uri $uri/ /index.html;
    }

    # French
    location /fr/ {
        alias /usr/share/nginx/html/fr/;
        try_files $uri $uri/ /fr/index.html;
    }

    # Arabic
    location /ar/ {
        alias /usr/share/nginx/html/ar/;
        try_files $uri $uri/ /ar/index.html;
    }

    # Spring Boot API
    location /api/ {
        proxy_pass http://backend:8080/api/;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}